### ISSUE TITLE
Nepoužívat oba guardy

### ISSUE THREAD

**Issue by fan1x** [dburian/cpp_mfo#1]
https://github.com/dburian/cpp_mfo/blob/4650d8404ace6d16ec32ac454bb16c9558debe4b/include/controller.h#L3

Je zbytečné a dokonce i možná nevhodné používat oba guardy dohromady - buď jedno nebo druhé

**Comment by dburian** [comment]
Odstranil jsem #pragma once v 2f989d1798bbf41165e67a275d9fc92deb243133
