### ISSUE TITLE
Proč jsi dělal vlastní thread_pool a nepoužil třeba async?

### ISSUE THREAD

**Issue by fan1x** [dburian/cpp_mfo#2]

**Comment by dburian** [comment]
Asi hlavní důvod byl, že jsem si chtěl thread pool vyzkoušet sám. O async jsem věděl jen z dvou Stroustrupových knížek a z přednášky a z toho co vím je to záhadný mechanizmus, který rozhoduje o spouštění nových vláken. Věděl jsem, že přesně něco takového chci, ale trošku mi vadilo, že nevím jak to vlastně funguje a prakticky neexistuje možnost jak async ovlivnit krom nastavení launch::deffered nebo launch::async. Navíc mi bylo jasné, že v budoucnu by bylo těžké takový jednoduchý a obecný mechanizmus nakonfigutovat na moje použití. Uznávám, že jsem mohl thread_pool naimplementovat tak, že používá async a tím se vyhnout záludnostem multithreadingu s využitím jeho rychlosti a s nastíněním budoucí pravděpodobné architektury.
