### ISSUE TITLE
Proč se vyplatí třídit jednovláknově? Od kolika prvků?

### ISSUE THREAD

**Issue by fan1x** [dburian/cpp_mfo#5]
https://github.com/dburian/cpp_mfo/blob/4650d8404ace6d16ec32ac454bb16c9558debe4b/doc/log.txt#L277

**Comment by dburian** [comment]
Přiznávám, že tomuto tématu jsem nevěnoval až tak velkou pozornost. Po nějaké chvíli jsem si uvědomil, že třízení jako takové nezapadá koncepčně do knihovny a tak jsem mu nevěnoval takovou pozornost a dokonce jsem tuto funkcionalitu z knihovny úplně vynechal s tím, že pro uživatele bude pravděpodobně daleko jednodušší používat std.

Své závěry v logu jsem učinil z tohoto dokumentu http://www.diva-portal.org/smash/get/diva2:839729/FULLTEXT02. Je to experiment srovnávání časů třídění v Javě na nějakém (dnes už docela základním) stroji - detaily v dokumentu.

**Comment by fan1x** [comment]
Fakt jsem jenom proletnul ty grafy z toho clanku, ale prijde mi, ze na 4 threadech az na Bucket sort se to vzdycky vyplatilo :)

**Comment by dburian** [comment]
Já to taky moc neprostudovával. Uvažoval jsem tak, že průměrný adresář bude mít do 256 souborů (nebo podadresářů) a pro tyto případy byla vždycky jednovláknová varianta nejrychlejší (tedy dle zdroje). Je možné že v C++ mají vlákna menší overhead a tak by třídit s víc vlákny dávalo smysl, ale na to jsem moc nesázel. Ikdyby tak by bylo zrychlení minimální (pár milisekund) a program by se tím dost zesložitil. I takhle zpětně mi to nepřipadá jako tak velká nevýhoda/vada knihovny.
