### ISSUE TITLE
Úplně jsem zatím ještě nepochopil, co a kdy tedy umíš paralelizovat?

### ISSUE THREAD

**Issue by fan1x** [dburian/cpp_mfo#6]
Co všechno umíš paralelizovat? Čekal jsem, že to bude umět paralelizovat všechny věci mezi ssebou nebo jednotlivé věci. Například `copy` akorát ale zavolá `fs::copy()`???

**Comment by dburian** [comment]
Jádro paralelizace je v controlleru, né v namespacu operate. Namespace operate představuje množinu jednovláknových tasků, které se budou používat při vícevláknovém používání knihovny.

Knihovna umí paralelizovat operace nad více soubory. Tedy například pokud uživatel bude chtít zkopírovat dva různé soubory na dvě různá místa, knihovna se může rozhodnout práci rozdělit (v optimalizéru) do dvou vláken a ty pak poběží paralelně. Každá operace generuje jedno až num_of_threads (v kódu) vláken, které se spustí a přesunou do thread_poolu. Můžou tedy například zároveň běžet vlákna kopírování, vyhledávání a přesouvání.

Doufal jsem že zrovna architektura bude dobře popsaná v logu. Konkrétně v druhé kapitole "Snahy a cíle" jsou úlohy jednotlivých komponent knihovny dobře popsány skrz pseudokód a komentáře.

**Comment by fan1x** [comment]
A umí to tedy automaticky paralelizovat, když budu například přesouvat/kopírovat složku -> nahledne do ní a najde si práci pro všechny thready?

**Comment by dburian** [comment]
To bohužel nedělá, což je docela velký mínus. Ze začátku jsem na to myslel, ale pak už jsem se spíš snažil úlohu spíš zjednodušit s tím, že se k tomu kdyžtak pak vrátím a nevrátil.
