### ISSUE TITLE
Drobet zlepšit dokumentaci

### ISSUE THREAD

**Issue by fan1x** [dburian/cpp_mfo#7]
Log je super. Jen jestli by šlo udělat na konec/na začátek nějaké finální shrnutí - jaká je finální architektura, jak paralelizuješ atd... 
Jinak, ideální místo pro dokumentaci na GITu je v README.md ;)

**Comment by dburian** [comment]
V cd83c988757b3a575b9eb8b0e5be79d32d50b497 jsem v logu připsal na konec pár shrnujících řádek, ale mám pocit, že už se pouze opakuji a neříkám nic nového. Mám pocit že v dokumentaci vše je, stačí si jen najít danou pasáž. Pokud se mnou tedy nebudeš souhlasit, asi budeš muset říct co přesně Ti chybí nebo se na konkrétní věc zeptat abych to mohl dopsat nebo ti konkrétně odpovědět, jelikož jsem asi už ve svý bublině.

Jinak o readme vím, jen se mi nechtělo učit se markdown. Vím že je to jednoduchý jazyk ale .txt je prostě jednodušší. Každopádně díky za tip do budoucna.

**Comment by fan1x** [comment]
> Mám pocit že v dokumentaci vše je, stačí si jen najít danou pasáž.
No to sice asi jo, ale fakt se mi nechce číst 500 řádků navíc dost z jsou Tvoje myšlenkové pochody, které jsou pro tebe super, ale mě, jako "zákazníka" vlastně ve finální implementaci nezajímají :) 
Ale to finální shrnutí je fajn, něco takové jsem chtěl vidět 👍

**Comment by dburian** [comment]
Chápu, to bylo ode mě nefér. Měl jsem normálně napsat dokumentaci a nenutit tě si tam něco hledat 😊.
